### ISSUE TITLE
Exception (sometimes) when sending E-Mails with attachments

### ISSUE THREAD

**Issue by CommandersEdge** [ESC-BV/FluentEmail.Graph#260]
Hi,

actually the title says everything.
I stumbled over this problem and was very confused, because it was hard to catch.

It's not randomly, because mails, which are failing, will always fail but some mails are sended without any problems.

System.NotSupportedException: Specified method is not supported.
   at System.Net.Http.HttpBaseStream.get_Length()
   at FluentEmail.Graph.GraphSender.SendWithAttachments(IFluentEmail email, CancellationToken cancellationToken) in /_/src/FluentEmail.Graph/GraphSender.cs:line 115
   at FluentEmail.Graph.GraphSender.SendAsync(IFluentEmail email, Nullable`1 token) in /_/src/FluentEmail.Graph/GraphSender.cs:line 58

**Comment by CommandersEdge** [comment]
I'm back and it was my mistake.

I did not safely copy the stream from System.Net.Http.HttpClient.GetStreamAsync() to a MemoryStream.

After I changed this, everything was fine.
